name       : gobject-introspection
version    : 1.62.0
release    : 21
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.62/gobject-introspection-1.62.0.tar.xz : b1ee7ed257fdbc008702bdff0ff3e78a660e7e602efa8f211dc89b9d1e7d90a2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
builddeps  :
    - pkgconfig(python3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
