name       : gobject-introspection
version    : 1.60.1
release    : 19
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.60/gobject-introspection-1.60.1.tar.xz : d844d1499ecd36f3ec8a3573616186d36626ec0c9a7981939e99aa02e9c824b3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
builddeps  :
    - pkgconfig(python3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
