name       : gobject-introspection
version    : 1.52.0
release    : 14
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gobject-introspection/1.52/gobject-introspection-1.52.0.tar.xz : 9fc6d1ebce5ad98942cb21e2fe8dd67b722dcc01981840632a1b233f7d0e2c1e
license    :
    - LGPL-2.1
    - GPL-2.0
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
