name       : gobject-introspection
version    : 1.54.1
release    : 16
source     :
    - https://ftp.acc.umu.se/pub/gnome/sources/gobject-introspection/1.54/gobject-introspection-1.54.1.tar.xz : b88ded5e5f064ab58a93aadecd6d58db2ec9d970648534c63807d4f9a7bb877e
license    :
    - LGPL-2.1
    - GPL-2.0
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
