name       : gobject-introspection
version    : 1.69.0
release    : 29
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.69/gobject-introspection-1.69.0.tar.xz : c668cbe4a3aad7539e2cf669ab576ce7fbadac6890472f4095ca215dbbebee99
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
builddeps  :
    - pkgconfig(python3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
