name       : gobject-introspection
version    : 1.50.0
release    : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.50/gobject-introspection-1.50.0.tar.xz : 1c6597c666f543c70ef3d7c893ab052968afae620efdc080c36657f4226337c5
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Generate interface introspection data for GObject libraries
component  : system.base
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
