name       : gobject-introspection
version    : 1.56.1
release    : 17
source     :
    - https://download.gnome.org/sources/gobject-introspection/1.56/gobject-introspection-1.56.1.tar.xz : 5b2875ccff99ff7baab63a34b67f8c920def240e178ff50add809e267d9ea24b
license    :
    - LGPL-2.1
    - GPL-2.0
component  : system.base
summary    : Generate interface introspection data for GObject libraries
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
