name       : gobject-introspection
version    : 1.48.0
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.48/gobject-introspection-1.48.0.tar.xz : fa275aaccdbfc91ec0bc9a6fd0562051acdba731e7d584b64a277fec60e75877
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Generate interface introspection data for GObject libraries
patterns   :
    - devel :
        - /usr/share/gobject-introspection-1.0
        - /usr/share/aclocal
devel      : yes
description: |
    GObject Introspection is a project for providing machine readable introspection data of the API of C libraries. This introspection data can be used in several different use cases, for example automatic code generation for bindings, API verification and documentation generation.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
